name: Deploy to EKS

on:
  push:
    branches: [main]

jobs:
  deploy:
    runs-on: ubuntu-latest

    steps:
    - name: Checkout source
      uses: actions/checkout@v3

    - name: Configure AWS credentials (without OIDC)
      uses: aws-actions/configure-aws-credentials@v2
      with:
        aws-access-key-id: ${{ secrets.AWS_ACCESS_KEY_ID }}
        aws-secret-access-key: ${{ secrets.AWS_SECRET_ACCESS_KEY }}
        aws-region: us-east-1

    - name: Update kubeconfig
      run: aws eks update-kubeconfig --region us-east-1 --name intel-io-test-cluster

    - name: Verify EKS access
      run: kubectl get nodes

    - name: Deploy Applications and LoadBalancers
      run: |
        # Deploy app1 and app2 deployments
        kubectl apply -f k8s/app1-deployment.yaml
        kubectl apply -f k8s/app2-deployment.yaml

        # Optional: Ingress (if using ALB Ingress Controller)
        kubectl apply -f k8s/ingress.yaml
